### ISSUE TITLE
max/min macro trouble

### ISSUE THREAD

**Issue by sethalves** [atollk/copper#12]
Building a project that includes copper.h on Windows with Microsoft's clang:

clang version 11.0.0
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: c:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\Llvm\x64\bin

I get this:

./copper.h(206,80): error: too few arguments provided to function-like macro invocation
explicit channel_buffer(size_t max_size = std::numeric_limits<size_t>::max()) : _max_size(max_size) {}
^
C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared\minwindef.h(193,9): note: macro 'max' defined here
#define max(a,b)            (((a) > (b)) ? (a) : (b))

**Comment by atollk** [comment]
Fixed by #15
