### ISSUE TITLE
ms abi warnings, unused variable warnings

### ISSUE THREAD

**Issue by sethalves** [atollk/copper#16]
with this clang:

Ubuntu clang version 11.0.0-2
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

I get warnings like these:

./copper.h:876:12: warning: class 'waiting_op_group_base' was previously declared as a struct; this is valid, but may result in linker errors under the Microsoft C++ ABI [-Wmismatched-tags]
    friend class waiting_op_group_base;
           ^
./copper.h:274:8: note: previous use is here
struct waiting_op_group_base {
       ^
./copper.h:876:12: note: did you mean struct here?
    friend class waiting_op_group_base;
           ^~~~~
           struct
./copper.h:980:12: warning: class 'waiting_op_group_base' was previously declared as a struct; this is valid, but may result in linker errors under the Microsoft C++ ABI [-Wmismatched-tags]
    friend class waiting_op_group_base;
           ^
./copper.h:274:8: note: previous use is here
struct waiting_op_group_base {
       ^
./copper.h:980:12: note: did you mean struct here?
    friend class waiting_op_group_base;
           ^~~~~
           struct
./copper.h:1649:10: warning: unused variable 'l' [-Wunused-variable]
    auto l = {(f(Is, std::get<Is>(t)), 0)...};

**Comment by atollk** [comment]
Fixed by #17
